services:
  db:
    container_name: !reset null

  x2crm:
    container_name: !reset null
    ports: !override
      - "18080:80"

  integration:
    container_name: !reset null

  wa_hub:
    container_name: !reset null

  caddy:
    container_name: !reset null
    ports: !override
      - "18081:80"
      - "18443:443"
